swagger: '2.0'
info:
  title: NLP Simple Tasks
  description: prototype for NLP Web services architecture
  version: "0.0.1"
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /{framework}/sentences:
    post:
      consumes:
      - text/plain
      summary: Split a document in sentences using the provided
      description: |
        This method splits the document in sentences.
      parameters:
        - name: framework
          in: path
          description: Which framework to use. Currently supports Apache OpenNLP and Stanford NLP
          required: true
          type: string
          enum: [openNLP, stanford]
        - name: body
          in: body
          required: true
          schema:
            type: string
            example: |
              this is sent one. this is sent two. and three! what about four?
      responses:
        200:
          description: An array of sentences (strings)

  /{framework}/tokens:
    get:
      summary: splits a single sentence into tokens
      description: |
        splits a single sentence into tokens
      parameters:
        - name: framework
          in: path
          description: Which framework to use. Currently supports Apache OpenNLP and Stanford NLP
          required: true
          type: string
          enum: [openNLP, stanford]
        - name: sentence
          in: query
          description: Sentence to parse into tokens.
          required: true
          type: string
      responses:
        200:
          description: An array of tokens (strings)
